### ISSUE TITLE
rust autoconf problem

### ISSUE THREAD

**Issue by SchrodingerZhu** [SchOJ/judge#6]
The compiler will update `cargo` repo data at the first time we compile `rust` source files (usually in `autoconf` period) and this may lead to timeout failure. Is there a way to solve it? For example, add a command when building docker image.

**Comment by outloudvi** [comment]
Done in [SchOJ/dmoj-judge::2566d7ef](https://github.com/SchOJ/dmoj-judge/commit/2566d7ef8ec3a80ae6f8f323d8c7e25708156012#diff-3254677a7917c6c01f55212f86c57fbf).
